FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc-arm-linux-gnueabihf \
       libc6-dev-armhf-cross zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
